/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Coupon`; params?: Router.UnknownInputParams; } | { pathname: `/EmailLogin`; params?: Router.UnknownInputParams; } | { pathname: `/Favorites`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/MembershipScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Notice`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Review`; params?: Router.UnknownInputParams; } | { pathname: `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/Support`; params?: Router.UnknownInputParams; } | { pathname: `/address`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orderlist` | `/orderlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage` | `/mypage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Coupon`; params?: Router.UnknownOutputParams; } | { pathname: `/EmailLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/Favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/MembershipScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Notice`; params?: Router.UnknownOutputParams; } | { pathname: `/Privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/Review`; params?: Router.UnknownOutputParams; } | { pathname: `/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `/Support`; params?: Router.UnknownOutputParams; } | { pathname: `/address`; params?: Router.UnknownOutputParams; } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ai` | `/ai`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orderlist` | `/orderlist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mypage` | `/mypage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Coupon${`?${string}` | `#${string}` | ''}` | `/EmailLogin${`?${string}` | `#${string}` | ''}` | `/Favorites${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/MembershipScreen${`?${string}` | `#${string}` | ''}` | `/Notice${`?${string}` | `#${string}` | ''}` | `/Privacy${`?${string}` | `#${string}` | ''}` | `/Review${`?${string}` | `#${string}` | ''}` | `/Signup${`?${string}` | `#${string}` | ''}` | `/Support${`?${string}` | `#${string}` | ''}` | `/address${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ai${`?${string}` | `#${string}` | ''}` | `/ai${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orderlist${`?${string}` | `#${string}` | ''}` | `/orderlist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mypage${`?${string}` | `#${string}` | ''}` | `/mypage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Coupon`; params?: Router.UnknownInputParams; } | { pathname: `/EmailLogin`; params?: Router.UnknownInputParams; } | { pathname: `/Favorites`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/MembershipScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Notice`; params?: Router.UnknownInputParams; } | { pathname: `/Privacy`; params?: Router.UnknownInputParams; } | { pathname: `/Review`; params?: Router.UnknownInputParams; } | { pathname: `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `/Support`; params?: Router.UnknownInputParams; } | { pathname: `/address`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ai` | `/ai`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orderlist` | `/orderlist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mypage` | `/mypage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
